### ISSUE TITLE
Timezone and daylight impact on now()

### ISSUE THREAD

**Issue by jeanmatthieud** [gmag11/NtpClient#13]
Hi,

After trying your lib (which is great btw), I realized that adding a timezone and the daylight mode have an impact on the time returned by now().

now() value should be in UTC (as a timestamp is always in UTC); only the value in string should be impacted by the daylight and the timezone.

**Comment by gmag11** [comment]
Yes, it is as I designed it. I want to have information on my local time without any calculation out of library. Time zone is always available using `getTimeZone()` so you can calculate UTC easily. If you want to get always UTC time from `now()` you can start NTPClient using 0 time zone and disabling DST.

**Comment by jeanmatthieud** [comment]
Thank you for your answer.
I think that this behavior is quite confusing for the end-user (it has been confusing at least for me) and should be documented.

**Comment by gmag11** [comment]
I did this library for myself during my free time as this is not my job. As I liked the result I shared it so that anyone can use it or modify it as their needs. I have to thank @PaulStoffregen for developing Time library that I use.
If you do not like how it behaves you can adapt to your needs if you know how to do it or ask for help if you don't. But, please, do not complain about something that is given to you for free.

Get my very best regards

**Comment by RudyFiero** [comment]
Your effort is much appreciated Germán.

**Comment by jeanmatthieud** [comment]
Sorry if I led you to think that I'm complaining. It is not the case, I really appreciate your work, and I hope that this thread will help other users to use your work.
Thanks again.

**Comment by gmag11** [comment]
You're wellcome. Thanks to you.
