### ISSUE TITLE
Get time kept without syncing with NTP server

### ISSUE THREAD

**Issue by papaiatis** [gmag11/NtpClient#14]
There are a bunch of helper methods that return the time/date in a formatted string, however I found only the `getTime()` method which returns the time in `time_t` format. However I see that this method synchronizes with the NTP server. 
I need such a method, that returns the time in `time_t` format but it does not synchronizes just returns the time kept (timekeeping since last sync).
It may be the `now()` method but it is not accessible from outside the class.

**Comment by papaiatis** [comment]
Just figured out that `#include "TimeLib.h"` comes with the `now()` method and I should call it directly and not through the NTP Client object.
Closing as of resolved.

**Comment by gmag11** [comment]
You have figured right. This lib purpose is only keep time synchronized with NTP and, additionally, format time and date as strings. It has no other local than my own one, but it can be easily modified.

`getTime()` triggers a NTP sync. This function is not intended to be called from your code (although there is no problem if you do it) because it is automatically called every period that it is configured (1800s by default, defined by `DEFAULT_NTP_INTERVAL` or configured in `begin()` method call).

Time is accounted by TimeLib so `now()` is the correct method to get Linux format time.
